### ISSUE TITLE
Add Codechef Option in constraint Blocking

### ISSUE THREAD

**Issue by sumantopal07** [sumantopal07/Constraints-Blocker-Chrome-Extension#2]
Codechef one is very similar to the leetcode.js file's code, refer to it to add the functionality.

**Comment by VishvaP** [comment]
@sumantopal07 Assign this issue to me

**Comment by sumantopal07** [comment]
> @sumantopal07 Assign this issue to me

assigned

**Comment by sumantopal07** [comment]
issue resolved #6
